name: samsung_prism
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  font_awesome_flutter: ^10.7.0
  country_flags: ^3.0.0
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2
  
  # QR and Barcode
  mobile_scanner: ^3.5.5
  qr_flutter: ^4.1.0
  
  # Internationalization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  
  # Storage
  shared_preferences: ^2.3.2
  
  # Location
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  
  # State Management
  provider: ^6.1.2
  
  # Network
  http: ^1.1.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10+1
  
  # Media
  image_picker: ^1.1.2
  
  # Data Visualization
  fl_chart: ^0.69.0
  
  # Animations
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.6.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/fonts/
    - assets/animations/
    - assets/translations/
    
  generate: true
