// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByf_qy7ErrehJrhOtlHA_-qphdhDFwJjI',
    appId: '1:75576999025:web:8c38ed5aa6bd8682e92fd0',
    messagingSenderId: '75576999025',
    projectId: 'samsung-prism-banking-app',
    authDomain: 'samsung-prism-banking-app.firebaseapp.com',
    storageBucket: 'samsung-prism-banking-app.firebasestorage.app',
    measurementId: 'G-4B5KT3D79Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT-bZcAuGwoqemR4O-QDjzMXEiGBrQ5xQ',
    appId: '1:75576999025:android:e7f8a301394e8fe9e92fd0',
    messagingSenderId: '75576999025',
    projectId: 'samsung-prism-banking-app',
    storageBucket: 'samsung-prism-banking-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh7CQfljsY9c7jfRBzbWcV8GRCmV630CY',
    appId: '1:75576999025:ios:87e903976a37a3c4e92fd0',
    messagingSenderId: '75576999025',
    projectId: 'samsung-prism-banking-app',
    storageBucket: 'samsung-prism-banking-app.firebasestorage.app',
    iosBundleId: 'com.example.samsungPrism',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh7CQfljsY9c7jfRBzbWcV8GRCmV630CY',
    appId: '1:75576999025:ios:87e903976a37a3c4e92fd0',
    messagingSenderId: '75576999025',
    projectId: 'samsung-prism-banking-app',
    storageBucket: 'samsung-prism-banking-app.firebasestorage.app',
    iosBundleId: 'com.example.samsungPrism',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByf_qy7ErrehJrhOtlHA_-qphdhDFwJjI',
    appId: '1:75576999025:web:2f4191890c08ecc0e92fd0',
    messagingSenderId: '75576999025',
    projectId: 'samsung-prism-banking-app',
    authDomain: 'samsung-prism-banking-app.firebaseapp.com',
    storageBucket: 'samsung-prism-banking-app.firebasestorage.app',
    measurementId: 'G-E3NMKXE7FY',
  );
}
